# Generated by Django 5.2.15 on 2026-06-23 10:59

import agronomy_club.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abbrev", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="chapter_logos/default.png",
                        null=True,
                        upload_to="chapter_logos/",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("desc", models.TextField(max_length=5000)),
                ("email", models.EmailField(max_length=255)),
                (
                    "colour",
                    colorfield.fields.ColorField(
                        default=agronomy_club.models.random_color,
                        image_field=None,
                        max_length=25,
                        samples=None,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
