# Generated by Django 5.2.15 on 2026-06-24 17:17

import agronomy_club.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0002_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceTypeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        upload_to=agronomy_club.models.resource_upload_path
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="agronomy_club.chapters",
                    ),
                ),
                (
                    "type_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resources",
                        to="agronomy_club.resourcetypetag",
                    ),
                ),
            ],
        ),
    ]
