# Generated by Django 5.2.15 on 2026-06-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0002_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("public", models.BooleanField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("quiz_data", models.JSONField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agronomy_club.chapters",
                    ),
                ),
            ],
        ),
    ]
