# Generated by Django 5.2.15 on 2026-06-25 04:32

import agronomy_club.models
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0002_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceTypeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default=agronomy_club.models.random_color,
                        image_field=None,
                        max_length=25,
                        samples=None,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="agronomy_club.chapter",
                    ),
                ),
                (
                    "type_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resources",
                        to="agronomy_club.resourcetypetag",
                    ),
                ),
            ],
        ),
    ]
