# Generated by Django 5.2.15 on 2026-06-26 07:37

import agronomy_club.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0003_resourcetypetag_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "grad_yr",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            agronomy_club.models.max_value_curr_year,
                        ]
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "global_role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("alumni", "Alumni"),
                            ("user", "User"),
                        ],
                        default="user",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
