# Generated by Django 5.2.15 on 2026-07-02 16:24

import agronomy_club.models
import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0005_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcetypetag",
            name="color",
            field=colorfield.fields.ColorField(
                default=agronomy_club.models.random_color_resource_tag,
                image_field=None,
                max_length=25,
                samples=None,
                unique=True,
            ),
        ),
    ]
