# Generated by Django 5.2.15 on 2026-07-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0005_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMemberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('chapter_role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')],
                                                  default='member', max_length=100)),
                ('position', models.CharField(choices=[('pres', 'President'),
                                                       ('vpres', 'Vice President'),
                                                       ('sec', 'Secretary'),
                                                       ('treas', 'Treasurer'),
                                                       ('ocm', 'Ordinary Committee Member')], default='pres', max_length=100)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='chapter_memberships', to='agronomy_club.chapters')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships',
                                              to='agronomy_club.users')),
            ],
        ),
    ]
