# Generated by Django 5.2.15 on 2026-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0006_chaptermemberships"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcetypetag",
            name="color",
        ),
        migrations.AddField(
            model_name="resourcetypetag",
            name="lucide_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
