# Generated by Django 5.2.15 on 2026-07-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0007_mock_resource_type_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapters",
            name="abbrev",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chapters",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chapters",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
