# Generated by Django 5.2.15 on 2026-07-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0007_mock_resource_type_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapters",
            name="abbrev",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chapters",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chapters",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="chapter_logo/<django.db.models.fields.CharField>.png",
                null=True,
                unique=True,
                upload_to="chapter_logos/",
            ),
        ),
        migrations.AlterField(
            model_name="chapters",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
