# Generated by Django 5.2.15 on 2026-07-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0008_mock_resource_type_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="abbrev",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("logo", "chapter_logos/default.png"), _negated=True
                ),
                fields=("logo",),
                name="unique_logo_except_default",
            ),
        ),
    ]
