# Generated by Django 5.2.15 on 2026-07-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0008_alter_chapters_abbrev_alter_chapters_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="eventurl",
            field=models.URLField(default="#", max_length=255),
        ),
    ]
