# Generated by Django 5.2.15 on 2026-07-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0009_event_eventurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="eventurl",
            field=models.URLField(default="#", max_length=255),
        ),
    ]
