# Generated by Django 5.2.16 on 2026-07-15 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0009_alter_chapters_abbrev_alter_chapters_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_data',
            field=models.FileField(upload_to='quiz_data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
