# Generated by Django 5.2.16 on 2026-07-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0009_user_password_and_membership_constraints"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chapters",
            new_name="Chapter",
        ),
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
        migrations.AlterModelTable(
            name="chapter",
            table="agronomy_club_chapters",
        ),
        migrations.AlterModelTable(
            name="user",
            table="agronomy_club_users",
        ),
    ]
