# Generated by Django 5.2.16 on 2026-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0010_alter_quiz_quiz_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
