# Generated by Django 5.2.16 on 2026-07-20 01:12

import agronomy_club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0010_alter_quiz_quiz_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=agronomy_club.models.User.create_photo_path,
            ),
        ),
    ]
