# Generated by Django 5.2.16 on 2026-07-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0009_alter_quiz_quiz_data"),
        ("agronomy_club", "0010_rename_chapters_chapter_rename_users_user_and_more"),
    ]

    operations = []
