# Generated by Django 5.2.16 on 2026-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0010_alter_quiz_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
