# Generated by Django 5.2.16 on 2026-07-20 04:41

import agronomy_club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0011_users_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaptermemberships",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Unspecified"),
                    ("pres", "President"),
                    ("vpres", "Vice President"),
                    ("sec", "Secretary"),
                    ("treas", "Treasurer"),
                    ("mark", "Marketing Officer"),
                    ("ocm", "Ordinary Comittee Member"),
                ],
                default="Unspecified",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="chaptermemberships",
            constraint=models.CheckConstraint(
                condition=models.Q(("chapter_role__in", agronomy_club.models.Role)),
                name="valid_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaptermemberships",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position__in", agronomy_club.models.Position),
                    ("position", ""),
                    _connector="OR",
                ),
                name="valid_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaptermemberships",
            constraint=models.UniqueConstraint(
                fields=("user_id", "chapter_id"), name="unique_user_chapter"
            ),
        ),
        migrations.AddConstraint(
            model_name="chaptermemberships",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("position__in", ["ocm", "mark", ""]), _negated=True
                ),
                fields=("chapter_id", "position"),
                name="unique_chapter_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaptermemberships",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("chapter_role", "member"), _negated=True),
                    ("position", ""),
                    _connector="OR",
                ),
                name="member_cant_have_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaptermemberships",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position__in", agronomy_club.models.Position),
                    ("chapter_role", "member"),
                    _connector="OR",
                ),
                name="owner_admin_must_have_position",
            ),
        ),
    ]
