# Generated by Django 5.2.16 on 2026-07-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0012_alter_chaptermemberships_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
