# Generated by Django 5.2.16 on 2026-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0012_alter_chaptermemberships_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chapter',
            name='unique_logo_except_default',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_logos/'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('logo__isnull', True), _negated=True),
                                                                  models.Q(('logo', ''), _negated=True)), fields=('logo',),
                                               name='unique_logo_except_null'),
        ),
    ]
