# Generated by Django 5.2.16 on 2026-07-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0012_alter_chaptermemberships_position_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chapters",
            name="unique_logo_except_default",
        ),
        migrations.AlterField(
            model_name="chapters",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="chapter_logos/"),
        ),
        migrations.AddConstraint(
            model_name="chapters",
            constraint=models.UniqueConstraint(
                condition=models.Q(("logo__isnull", False)),
                fields=("logo",),
                name="unique_logo_except_default",
            ),
        ),
    ]
