# Generated by Django 5.2.16 on 2026-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0013_remove_chapters_unique_logo_except_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='abbrev',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='desc',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
