# Generated by Django 5.2.16 on 2026-07-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0014_alter_chapters_abbrev_alter_chapters_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
