# Generated by Django 5.2.16 on 2026-07-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy_club", "0014_alter_chapters_abbrev_alter_chapters_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discipline",
            field=models.CharField(max_length=30),
        ),
    ]
